version: "3.7"
services:
    app:
        build:
            args:
                user: git
                password: Rn742NrLiE2
                uid: 1401
            context: ./
            dockerfile: ecommpay-app.dockerfile
        image: ecommpay-app
        container_name: ecommpay-app
        restart: unless-stopped
        working_dir: /var/www/html
        networks:
            - ecommpay-network
        ports:
            - '9015:9001'
        volumes:
            - web_root:/var/www/html
    nginx:
        image: nginx:1.17-alpine
        container_name: ecommpay-app-nginx
        restart: unless-stopped
        ports:
            - 8021:80
        volumes:
            - web_root:/var/www/html
            - ./.docker-conf/nginx:/etc/nginx/conf.d
        networks:
            - ecommpay-network
networks:
    ecommpay-network:
        driver: bridge

volumes:
    web_root:
    cache:
        driver: local

